# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/150lrX79uCSFIKQrFWI5qdQR2Yy9RaXtq
"""

import cv2

video = cv2.VideoCapture(0)

while True:
	ret, frame = video.read()
	cv2.imshow("Frame", frame)
	k = cv2.waitKey(1)
	if k == ord('q'):
		break

video.release()
cv2.destroyAllWindows()